sudo: false
language: ruby
rvm:
  - 2.5.1
node_js:
  - "node"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - script:
      - bin/test
    - script:
      - travis_retry bin/link-check
